#!/usr/bin/bash

if [ -e ~/scripts-data/auto-dark/sun_times ]; then
  sunrise=`head -n1 ~/scripts-data/auto-dark/sun_times`
  sunset=`tail -n1 ~/scripts-data/auto-dark/sun_times`
fi

currenttime=$(date -u +%H:%M:%S)
if [[ "$sunrise" != "" ]] && [[ "$sunset" != "" ]] && ( [[ "$currenttime" < "$sunrise" ]] || [[ "$currenttime" > "$sunset" ]] ); then
  /usr/bin/google-chrome-stable --enable-features=WebUIDarkMode --force-dark-mode $@
else
  /usr/bin/google-chrome-stable $@
fi
