#!/usr/bin/bash

set -e

#sleep 5 # żeby się podłączył do sieci
# Warszawa
lat=52.25
lng=21.00

curl "https://api.sunrise-sunset.org/json?lat=$lat&lng=$lng&formatted=0" > ~/scripts-data/auto-dark/sun_times.json
cat ~/scripts-data/auto-dark/sun_times.json | jq -r .results.sunrise | sed -e 's/.*T//' -e 's/+00:00//' > ~/scripts-data/auto-dark/sun_times_curr
cat ~/scripts-data/auto-dark/sun_times.json | jq -r .results.sunset  | sed -e 's/.*T//' -e 's/+00:00//' >> ~/scripts-data/auto-dark/sun_times_curr
cp ~/scripts-data/auto-dark/sun_times_curr ~/scripts-data/auto-dark/sun_times
