#!/usr/bin/bash

set -e

sleep 5 # żeby się podłączył do sieci
location=52.25,21.00 # Warszawa
curl -f -L https://weather.com/pl-PL/pogoda/dzisiaj/l/$location | sed 's/<span/\n/g' | sed 's/<\/span>/\n/g'  | grep -E "details-sunrise|details-sunset" | sed -e 's/.*>//g' > ~/scripts-data/auto-dark/sun_times_curr
cp ~/scripts-data/auto-dark/sun_times_curr ~/scripts-data/auto-dark/sun_times
